CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_id          BIGINT       NOT NULL,
    nickname          VARCHAR(50)  NOT NULL,
    profile_image_url VARCHAR(500),
    role              VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_kakao_id UNIQUE (kakao_id)
);

CREATE TABLE study_party (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id      BIGINT        NOT NULL,
    title         VARCHAR(100)  NOT NULL,
    description   TEXT,
    category      VARCHAR(30)   NOT NULL,
    capacity      INTEGER       NOT NULL,
    status        VARCHAR(20)   NOT NULL DEFAULT 'RECRUITING',
    open_chat_url VARCHAR(500)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_study_party_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_study_party_category ON study_party (category);
CREATE INDEX idx_study_party_status ON study_party (status);

CREATE TABLE party_member (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id  BIGINT    NOT NULL,
    user_id   BIGINT    NOT NULL,
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_party_member_party FOREIGN KEY (party_id) REFERENCES study_party (id) ON DELETE CASCADE,
    CONSTRAINT fk_party_member_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_party_member UNIQUE (party_id, user_id)
);

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    token      VARCHAR(500) NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_refresh_token_user_id UNIQUE (user_id)
);
