ALTER TABLE users ADD COLUMN class_no INTEGER;
ALTER TABLE users ADD COLUMN team_no INTEGER;
ALTER TABLE users ADD COLUMN real_name VARCHAR(20);
ALTER TABLE users ADD COLUMN profile_completed BOOLEAN NOT NULL DEFAULT FALSE;
