CREATE TABLE dinner_party (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id      BIGINT        NOT NULL,
    title         VARCHAR(100)  NOT NULL,
    description   TEXT,
    location      VARCHAR(100)  NOT NULL,
    meeting_at    TIMESTAMP     NOT NULL,
    capacity      INTEGER       NOT NULL,
    status        VARCHAR(20)   NOT NULL DEFAULT 'RECRUITING',
    open_chat_url VARCHAR(500)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dinner_party_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_dinner_party_status ON dinner_party (status);

CREATE TABLE dinner_party_member (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id  BIGINT       NOT NULL,
    user_id   BIGINT       NOT NULL,
    joined_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status    VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    CONSTRAINT fk_dinner_party_member_party FOREIGN KEY (party_id) REFERENCES dinner_party (id) ON DELETE CASCADE,
    CONSTRAINT fk_dinner_party_member_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_dinner_party_member UNIQUE (party_id, user_id)
);
