ALTER TABLE study_party ADD COLUMN recruitment_type VARCHAR(20) NOT NULL DEFAULT 'APPROVAL';
ALTER TABLE dinner_party ADD COLUMN recruitment_type VARCHAR(20) NOT NULL DEFAULT 'APPROVAL';
ALTER TABLE weekend_party ADD COLUMN recruitment_type VARCHAR(20) NOT NULL DEFAULT 'APPROVAL';
